linters:
  enable:
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - importas
    - makezero
    - misspell
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - testifylint
    - zerologlint
