version: '3'
tasks:

  up-k3d:
    desc: "Create a 'workbench' k3d cluster"
    cmds:
      - k3d cluster delete workbench
      - k3d cluster create workbench --registry-create workbench-registry --config .k3d.yaml
    status:
      - k3d cluster get workbench
      - "k3d cluster get workbench -oyaml | grep 'Running: true'"

  down-k3d:
    desc: "Delete the 'workbench' k3d cluster"
    cmds:
      - k3d cluster delete workbench

  up-tilt:
    desc: "Run the tilt dev server"
    deps:
      - up-k3d
    cmds:
      - tilt up

  up-dev:
    desc: "Set up the development environment"
    deps:
      - up-tilt

  down-dev:
    desc: "Tear down the development environment"
    deps:
      - down-k3d

  build-helm:
    desc: "Render the helm chart templates"
    cmds:
      - helm template local deploy/ --release-name --output-dir=deploy/rendered/

  build-api:
    desc: "Build the API container image"
    cmds:
      - docker build ./api -f ./api/build/Dockerfile -t workbench/api:latest

  build-product-store:
    desc: "Build the product-store container image"
    cmds:
      - docker build ./product-store -f ./product-store/build/Dockerfile -t workbench/product-store:latest

  run-redis-cli:
    desc: "Connect to the local dev cluster with redis-cli"
    cmds:
      - redis-cli
    env:
      REDISCLI_AUTH:
        sh: kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 -d

  test-api:
    desc: "Run the api tests"
    cmds:
      - pytest
