apiVersion: v1
kind: Service
metadata:
  name: {{ include "workbench.productStoreName" . }}
  labels:
    {{- include "workbench.productStoreLabels" . | nindent 4 }}
spec:
  type: {{ .Values.productStore.service.type }}
  ports:
    - port: {{ .Values.productStore.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workbench.productStoreSelectorLabels" . | nindent 4 }}
