# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/heads/main/configuration-schema.json

package: client
output: pkg/client/gen.go
generate:
  models: true
  client: true
output-options:
  skip-prune: true
import-mapping:
  ./types.spec.yaml: "product-store/pkg/types"
