# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/heads/main/configuration-schema.json

package: types
output: pkg/types/gen.go
generate:
  models: true
output-options:
  skip-prune: true
