apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-store.fullname" . }}
  labels:
    {{- include "product-store.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "product-store.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-store.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "product-store.serviceAccountName" . }}
      containers:
        - name: "product-store"
          image: "workbench/product-store:latest"
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: {{ include "product-store.redisHost" . | quote }}
            - name: REDIS_PORT
              value: {{ include "product-store.redisPort" . | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "product-store.redisSecretName" . }}
                  key: {{ include "product-store.redisSecretPasswordKey" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {}
