apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msgs.fullname" . }}
  labels:
    {{- include "msgs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "msgs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "msgs.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "msgs.serviceAccountName" . }}
      containers:
        - name: "msgs"
          image: "workbench/msgs:latest"
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: {{ include "msgs.redisHost" . | quote }}
            - name: REDIS_PORT
              value: {{ include "msgs.redisPort" . | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "msgs.redisSecretName" . }}
                  key: {{ include "msgs.redisSecretPasswordKey" . }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {}
